name: "Cache Volumes Benchmarking"
description: "Benchmark npm install performance with cache volumes"
steps:
  - label: "🚀 Generate simple benchmark pipeline"
    command: "./.buildkite/generate-pipeline.sh"
